[package]
name = "jex-sc-staking-v2-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["AurÃ©lien Passion <aurelien.passion@gmail.com>"]

[dev-dependencies]

[dependencies.jex-sc-staking-v2]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.64.1"
